version: "3"
services:
  app:
    image: rmaafs/rmaafs-api:latest
    ports:
      - "20202:20202"
    environment:
      VIRTUAL_HOST: api.rmaafs.com
    env_file: /root/.env/rmaafs-api/secrets.env
    restart: always
    volumes:
      - ./data:/data

networks:
  default:
    name: nginx-proxy
    external: true
